### ISSUE TITLE
[Issue] Some mods are unable to be overwritten by the modpack installer

### ISSUE THREAD

**Issue by RyanWalpole** [RyanWalpoleEnterprises/The-Potato-Farm-SDVM#124] opened 2024-04-03 03:10 UTC
### The Issue or Bug

Some mods (specifically DLL files) throw "The file already exists" when installing modpack updates.

### Version

240401

### Operating System

Windows 11

### Steps to reproduce the behavior

1. Install a modpack
2. Install the modpack again (should overwrite)
3. Experience issue.

### Log Files

[log_03-06-2024-02-06-42.log](https://github.com/RWELabs/Stardew-Valley-Mod-Manager/files/14846196/log_03-06-2024-02-06-42.log)
```
Stardew Valley Mod Manager v240401
(C) RWE Labs, 2022
-------------------- ERROR LOG --------------------
This log was generated at: 03-06-2024-02-06-42
With Stardew Valley Mod Manager version 240401

The application experienced an issue whilst trying to install the modpack: The file 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\inactive-mods\AlternativeTextures\AlternativeTextures.deps.json' already exists.
```

**Comment by RWELabs** [comment] 2024-04-06 03:37
Duplicate of #88 
Please refer to that issue for updates.

**Closed as completed** 2024-04-12 04:23 UTC
Labels: type: critical bug, type: implementation
